### ISSUE TITLE
jupyter notebook not working

### ISSUE THREAD

**Issue by nagendra-2k3** [vital987/code-server#1]

**Comment by vital987** [comment]
It's working fine, you need to mark your book as trusted, only the thing is I didn't installed its prerequisites so it will install install it everytime the dyno restarts, I will install it in the next release, and of course you'll not get the same performance on Heroku as local due storage and privilege limitations.
![ipynb](https://user-images.githubusercontent.com/82765893/121133130-97d19b00-c84f-11eb-8361-9d8ec3b10e64.png)

**Comment by nagendra-2k3** [comment]
thx man
r u from India

**Comment by vital987** [comment]
Yup. I am from India, and send I will make changes in Dockerfile, didn't thought of applying mind on RUN commands, thanks for suggesstion.:smile:
